name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Эти переменные помогают Testcontainers работать в GitHub Actions
      TESTCONTAINERS_RYUK_DISABLED: 'true'
      DOCKER_HOST: unix:///var/run/docker.sock

    steps:
      # ------------------------
      # 1. Клонируем репозиторий
      # ------------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # ------------------------
      # 2. Настройка JDK 24
      # ------------------------
      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      # ------------------------
      # 3. Проверка и подготовка gradlew
      # ------------------------
      - name: Show gradlew info
        run: |
          ls -la gradlew
          head -n 1 gradlew

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      # ------------------------
      # 4. Сборка и тесты с GitHub Packages
      # ------------------------
      - name: Build and test
        run: ./gradlew clean build --no-daemon
        env:
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test
