name: CI

on:
  push:
    branches: [ master ] # твоя ветка
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # ------------------------
    # 1. Добавляем сервисы Postgres и Kafka
    # ------------------------
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      kafka:
        image: bitnami/kafka:3.5.0
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_LISTENERS: PLAINTEXT://:9092
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
        ports:
          - 9092:9092
        options: >-
          --health-cmd="kafka-topics.sh --bootstrap-server localhost:9092 --list"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # ------------------------
      # 2. Клонируем репозиторий
      # ------------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # ------------------------
      # 3. Настройка JDK 24
      # ------------------------
      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      # ------------------------
      # 4. Подготовка gradlew
      # ------------------------
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      # ------------------------
      # 5. Build и тесты
      # ------------------------
      - name: Build and run tests
        run: ./gradlew build --no-daemon
        env:
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
